backend:
  name: github
  repo: Programmingjoe/Pictus

media_folder: static/assets
public_folder: /assets

collections:
  - name: block
    label: Block
    folder: src/data/blocks
    create: true
    fields:
      - { name: id, label: Id }
      - { name: title, label: Title, required: false }
      - { name: subtext, label: Subtext, required: false }
      - { name: body, label: Body, widget: text, required: false }
      - { name: image, label: Image, widget: image, required: false }
  - name: testimonial
    label: Testimonial
    folder: src/data/testimonials
    create: true
    fields:
      - { name: company, label: Company }
      - { name: person, label: Person }
      - { name: body, label: Body, widget: text }
      - { name: image, label: Image, widget: image }
      - { name: order, label: Order }
  - name: feature
    label: Feature
    folder: src/data/features
    create: true
    fields:
      - { name: title, label: Title }
      - { name: body, label: Body, widget: text }
      - { name: image, label: Image, widget: image }
      - { name: order, label: Order }
  - name: attribute
    label: Attribute
    folder: src/data/attributes
    create: true
    fields:
      - { name: title, label: Title }
      - { name: body, label: Body, widget: text }
      - { name: image, label: Image, widget: image }
      - { name: order, label: Order }
  - name: module
    label: Module
    folder: src/data/modules
    create: true
    fields:
      - { name: title, label: Title }
      - { name: requirement, label: Requirement, widget: text, required: false }
      - { name: body, label: Body, widget: text }
      - { name: image, label: Image, widget: image, required: false }
      - { name: order, label: Order }
      - { name: addOn, label: Add On, widget: boolean, default: false }
  - name: member
    label: Member
    folder: src/data/members
    create: true
    fields:
      - { name: title, label: Title }
      - { name: name, label: Name }
      - { name: image, label: Image, widget: image, required: false }
      - { name: order, label: Order }
      - { name: area, label: Area - DEVELOPMENT - INDUSTRY - COMM - LEADERSHIP }
